using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using System;
using System.Collections.Generic;

namespace CommonComponents
{
    public static class Constants
    {
        public static ExtentReports extent = new AventStack.ExtentReports.ExtentReports();
        public static ExtentTest test;
        public static ExtentTest feature;
        public static ExtentTest scenario;
        public static bool _testFailed;
        public static Dictionary<string, string> Properties;
        public static ExtentHtmlReporter htmlReporter;
        //  public static ExtentSparkReporter htmlReporter;
        public static int Failure = 0;
        public static int Passed = 0;
        public static List<string> Errors = new List<string>();
        public static string finaloccurance;
        public static string ReportsDir;
        public const string Table1 = "<tr style='height:15.0pt'><td width=95 nowrap style='width:100.0pt;border:solid windowtext 1.0pt;border-top:none;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><spanstyle='color:black'>";
        public const string Table2 = " &nbsp; <o:p></o:p></span></p></td><td width=95 nowrap align=center style='width:100.0pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><pclass=MsoNormal><span style='color:black'>";
        public const string Table3 = "<o:p></o:p></span></p></td></tr>";
        public const string Table4 = "<body lang=EN-US link=\"#0563C1\" vlink=\"#954F72\"><div class=WordSection1><p class=MsoPlainText><o:p>&nbsp;</o:p></p><table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=75 style='width:75.0pt;margin-left:-.4pt;border-collapse:collapse'><tr style='height:15.0pt'><td width=95 nowrap align=center style='width:75.0pt;border:solid windowtext 1.0pt;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style='color:white'>Components<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Last Modified Date<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>CheckSum<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Size Before<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Size After<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>File Version<o:p></o:p></span></b></p></td></tr>";
        public const string Table5 = "</table></div></body>";
        public const string Table6 = "<body lang=EN-US link=\"#0563C1\" vlink=\"#954F72\"><div class=WordSection1><p class=MsoPlainText><o:p>&nbsp;</o:p></p><table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=75 style='width:75.0pt;margin-left:-.4pt;border-collapse:collapse'><tr style='height:15.0pt'><td width=95 nowrap align=center style='width:75.0pt;border:solid windowtext 1.0pt;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style='color:white'>Build Exe's<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Last Modified Date<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>DiffHours/Days<o:p></o:p></span></b></p></td></tr>";
        public const string Table7 = "<body lang=EN-US link=\"#0563C1\" vlink=\"#954F72\"><div class=WordSection1><p class=MsoPlainText><o:p>&nbsp;</o:p></p><table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=75 style='width:75.0pt;margin-left:-.4pt;border-collapse:collapse'><tr style='height:15.0pt'><td width=95 nowrap align=center style='width:75.0pt;border:solid windowtext 1.0pt;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style='color:white'>Email Subject<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Alert Description<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>WorkStation<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>ARxProMMonitor Version<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>ARxProMListener Version<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>ARxPromLib Version<o:p></o:p></span></b></p></td></tr>";
        public const string Table8 = "<body lang=EN-US link=\"#0563C1\" vlink=\"#954F72\"><div class=WordSection1><p class=MsoPlainText><o:p>&nbsp;</o:p></p><table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=75 style='width:75.0pt;margin-left:-.4pt;border-collapse:collapse'><tr style='height:15.0pt'><td width=95 nowrap align=center style='width:75.0pt;border:solid windowtext 1.0pt;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style='color:white'>Database Name<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>RowCount<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>SQL<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Average(Milliseconds)<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Maximum(Milliseconds)<o:p></o:p></span></b></p></td><td width = 95 nowrap align = center style='width:125.0pt;border:solid windowtext 1.0pt;border-left:none;background:#A5A5A5;padding:0in 5.4pt 0in 5.4pt;height:15.0pt'><p class=MsoNormal><b><span style = 'color:white'>Minimum(Milliseconds)<o:p></o:p></span></b></p></td></tr>";
        public static DateTime starttime;
        public static Random rand = new Random();
    }
}
