using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using AventStack.ExtentReports.Gherkin.Model;
using iText.Layout.Properties;
using System.Windows.Forms;
using OpenQA.Selenium;
using Microsoft.Office.Interop.Outlook;

namespace CommonComponents
{
    public static class EI_ExamAnswers
    {

        //        public static Dictionary<string, string> EI_70_701_14_16_10_05_ES = new Dictionary<string, string>()
        //        {
        //            {"El principal foco de atención del trabajo del supervisor es generalmente","dirigir el trabajo de los empleados."},
        //{"¿Cuál de las siguientes afirmaciones acerca de los principios de administración es VERDADERA","Las altas tasas de rotación de personal llevan a la inestabilidad y la ineficiencia de una organización."},
        //{"¿Que es la autoridad formal","Es el poder que otorga la posición de una persona en la organización."},
        //{"¿Cuál de las siguientes afirmaciones acerca de la responsabilidad del supervisor es VERDADERA","Cuando el supervisor delega una tarea, él es el responsable final del desempeño del empleado."},
        //{"¿Cuál de los siguientes componentes de la gerencia involucra el reclutamiento de candidatos para los puestos vacantes y la contratación de los mejor clasificados","Selección de personal"},
        //{"¿Cuál de los siguientes resultados de la planificación de operaciones proveen detalles de cómo los gerentes deben generar ingresos y/o incurrir en gastos durante el próximo año","Un presupuesto de operaciones."},
        //{"¿Cuál es la razón primaria por la que los supervisores fallan","Por su incapacidad para tratar a sus empleados y relacionarse con ellos de forma eficaz."},
        //{"¿Cuál de las siguientes es una cualidad de un supervisor eficaz","Autoimagen y personalidad positivas."},
        //{"A veces, las personas tienden a emitir juicios inmediatos sobre una persona sobre la base de factores externos, tales como aspecto físico, acento y edad. Estos prejuicios sobre la “primera impresión” pueden afectar negativamente la comunicación. ¿Cómo se pueden minimizar o eliminar los prejuicios personales basados en primeras impresiones","Buscando más información acerca de la persona."},
        //{"¿Cuál de las siguientes es una barrera para la comunicación eficaz","Distracciones."},
        //{"La mejor forma de mantener la atención del oyente es","explicar cómo su mensaje afentará al oyente."},
        //{"¿Cuál de las siguientes afirmaciones acerca de la capacidad de escuchar es VERDADERA","Las personas pueden aprender a convertirse en buenos oyentes."},
        //{"Un empleado frustrado le dice “ ¡A mí nadie me ayuda. Siempre me dan los trabajos que nadie más quiere realizar. ¿Por qué aquí todos se aprovechan de mí todo el tiempo?” Usted, como supervisor, le responde “¿A usted le parece que las asignaciones de trabajos no son justas?“ ¿Cuál de las siguientes técnicas de escucha activa describe mejor su respuesta","Parafraseo"},
        //{"Cuando se escucha y se responde a un interlocutor, ¿cuál es el propósito de la técnica denominada “Autosinceramiento”","Ayudar al interlocutor a sentirse comprendido y menos solo."},
        //{"Cuál de las siguientes formas de comunicación se considera no verbal","hacer contacto visual."},
        //{"Como supervisor, ¿por qué debe tener tener en cuenta la comunicación no verbal cuando trata con empleados, compañeros y gerentes","Porque el lenguaje corporal puede revelar algo diferente de lo que están tratando de decir."},
        //{"Es mejor tratar de escribir en voz pasiva. ¿Cuál de las siguientes oraciones está escrita en voz pasiva","La decisión de contratar a Bill fue tomada por Laura."},
        //{"¿Cuál de los siguientes es un “departamento de línea”","Alimentos y bebidas."},
        //{"Con respecto al reclutamiento y la selección de personal, el departamento de recursos humanos","envía al supervisor los mejores precandidatos para la segunda entrevista."},
        //{"¿Cuál de las siguientes es una ventaja potencial del reclutamiento interno sobre el externo","El costo del reclutamiento interno es más bajo que el del reclutamiento externo."},
        //{"¿Cuál es una DESVENTAJA del reclutamiento interno","Llena una vacante en un departamento pero puede abrir otra más crítica en otro departamento."},
        //{"¿Cuál de las siguientes es una DESVENTAJA del reclutamiento externo","Es más difícil encontrar a alguien que se adapte a la cultura de la compañía y la filosofía de la gerencia cuando se recluta externamente."},
        //{"¿Cuál de los siguientes tipos de preguntas de una entrevista estimula a los candidatos a profundizar un tema y promueve una respuesta amplia","Preguntas abiertas o indirectas."},
        //{"¿Cuál de las siguientes es una pregunta cerrada o directa en una entrevista de trabajo","¿Disfrutó su trabajo anterior?"},
        //{"¿Qué debe hacer un entrevistador antes de reunirse con un candidato en una entrevista de trabajo","Revisar en detalle la solicitud de empleo en blanco, es decir sin cumplimentar."},
        //{"¿Cuál de las siguientes es una sugerencia para conducir una entrevista de selección de personal","Asegurarse de que el trabajo satisface las necesidades del candidato en cuanto a sueldo, beneficios, horario y condiciones de trabajo."},
        //{"Mariana está tratando de determinar si los beneficios de una sesión planificada de capacitación sobre diversidad pueden exceder sus costos. ¿Qué está haciendo Mariana","Calculando el retorno de la inversión."},
        //{"¿Cuál es una ventaja de la capacitación uno a uno","Otorga a los participantes atención individual y retroalimentación inmediata."},
        //{"___________ de la capacitación establecen lo que el participante debe saber o ser capaz de hacer después de completar la capacitación","Los objetivos"},
        //{"Después de completar la capacitación, el instructor debe permitir que el participante realice el procedimiento por las suyas. Esto se denomina","desempeño de prueba."},
        //{"¿Cuál de las siguientes actividades es parte del paso de “Seguimiento” en el método de capacitación de cuatro pasos","Enseñar cada día unas pocas tareas."},
        //{"Las personas aprenden mejor de acuerdo a su estilo de aprendizaje. ¿Qué tipo de participante aprende mejor cuando participa en forma física y activa","Participante táctil kinestésico."},
        //{"¿Cuál de los siguientes factores puede afectar el estilo de aprendizaje de los participantes y, a su vez, afectar la forma de presentar la capacitación","Todas las opciones anteriores."},
        //{"¿Cuál de los siguientes es un beneficio de la orientación general para el empleado","Ayudar a los empleados a entender las expectativas de la compañía acerca de su desempeño."},
        //{"¿Cuál de las siguientes afirmaciones acerca de las normas de productividad es VERDADERA","Es mejor determinar las tasas de productividad por puesto y turno que determinar una tasa de productividad general para toda la organización."},
        //{"¿Qué herramientas puede utilizar el supervisor para programar correctamente el número correcto de empleados que trabajan por día","Una guía de contratación de personal y un pronóstico del volumen de negocios."},
        //{"Jerónimo, el supervisor de catering del hotel City Center, utiliza un enfoque de ajuste de base para pronosticar las ventas y programar el personal. A fin de considerar la estacionalidad del negocio, Jerónimo debe","usar los datos del mismo periodo durante el año anterior como cifra base."},
        //{"Siempre que sea posible, los supervisores deben diseñar ____________ para cubrir las necesidades día a día (e incluso hora por hora) del volumen de negocios","horarios de trabajo"},
        //{"En general ¿por qué no es recomendable programar los horarios de los empleados para empezar y terminar los turnos al mismo tiempo","El flujo del trabajo varía y se necesitan más empleados durante las horas pico del negocio."},
        //{"Una técnica alternativa para programar el horario de los empleados que los supervisores pueden usar es la de turnos divididos. ¿Cuál de las siguientes afirmaciones describe un turno dividido","Programar un empleado para que trabaje durante dos períodos separados el mismo día."},
        //{"Juana, la nueva supervisora del departamento de limpieza del hotel King James, compara la guía de programación de personal actual con los costos de mano de obra presupuestados para los próximos meses. Su conclusión fue que si los horarios de trabajo se prepararon con la guía de programación de personal en uso, los gastos de personal podrían exceder consideramente el presupuesto. ¿Cuál de las siguientes es la acción más razonable que debería tomar Juana","Mantener los requisitos de calidad y aumentar las tasas de productividad."},
        //{"El supervisor del restaurante Rose Garden compara todos los días y todas las semanas las horas de trabajo reales de cada empleado contra las horas de trabajo que tenía programadas. El supervisor realiza esta comparación para","monitorear y evaluar el proceso de programación de horarios de trabajo."},
        //{"¿Cuál de las siguientes causas es aceptable para introducir una varianza entre las horas de trabajo programadas y las horas realmente trabajadas","Todas las anteriores son causas aceptables de una varianza."},
        //{"En este método comparativo de evaluación de desempeño, el supervisor hace una lista de sus empleados en la que coloca al mejor empleado en el primer lugar y al peor en el último lugar, luego pone al segundo mejor empleado en el segundo lugar de arriba hacia abajo y al segundo peor empleado en el segundo lugar de abajo hacia arriba. Continúa clasificando al resto de los empleados de la misma manera. Este método se conoce como enfoque de","clasificación alternativa."},
        //{"¿Cuál de las opciones siguientes es útil para medir el progreso hacia el logro de las metas de un empleado","establecer parámetros de comparación."},
        //{"A fin de prepararse para la evaluación de desempeño de un empleado un supervisor debe","recopilar información acerca de incidentes de trabajo que ha observado."},
        //{"¿Cuál es la definición de entrenamiento","Ayudar a los empleados a mejorar su desempeño en el trabajo brindándoles retroalimentación."},
        //{"¿Cuál es la diferencia entre consejería y entrenamiento","La consejería se ocupa de las actitudes o los problemas personales de los empleados, mientras que el entrenamiento ayuda a los empleados a mejorar su rendimiento en las tareas del trabajo."},
        //{"Una entrevista ____________ es un tipo de sesión de entrenamiento formal, donde el supervisor hace preguntas al empleado en un formato estructurado. El propósito es dar y recibir información o analizar sentimientos y actitudes","directiva"},
        //{"Durante  las sesiones de entrenamiento formal, el supervisor debe","explicar cómo el desempeño de un empleado cae por debajo de las expectativas."},
        //{"Los supervisores que temen disciplinar a los empleados se vuelven indulgentes y tienden a pasar por alto errores o reglas incumplidas. ¿Qué sucede frecuentemente como resultado","Los empleados pierden el respeto por el supervisor o pierden su lealtad hacia el departamento."},
        //{"¿Por qué es importante revisar las políticas, reglas y procedimientos","Para asegurar que sean razonables y los empleados los puedan cumplir."},
        //{"José ha llegado tarde un número significativo de veces. Como resultado, su supervisor lo llama a su oficina para discutir sus retrasos. Después de la reunión, el comportamiento de José mejora. ¿Cuándo debería el supervisor darle un refuerzo positivo","El supervisor debe darle un refuerzo positivo la siguiente mañana que llega a tiempo al trabajo."},
        //{"Normalmente, el primer paso en un proceso disciplinario es","un llamado de atención verbal."},
        //{"¿Cuál de las siguientes afirmaciones acerca de la disciplina progresiva es VERDADERA","Los programas de disciplina progresiva pueden variar notablemente en cuanto a la definición de los comportamientos sujetos a las acciones disciplinarias."},
        //{"¿Cuál de las siguientes preguntas debería considerarse antes de despedir a un empleado","¿Se comunicaron claramente al empleado las reglas pertinentes?"},
        //{"La entrevista de salida es conducida generalmente por","un gerente junto con otro gerente o con un representante de recursos humanos."},
        //{"Antes de decidir tomar una acción disciplinaria, ¿cuál de las siguientes preguntas debe hacerse un supervisor","¿El empleado sabía que rompía la regla?"},
        //{"En una sesión disciplinaria que lleva a cabo un supervisor, el empleado se torna molesto, defensivo, argumentativo y hostil. El supervisor debe","escuchar hasta que el empleado termine de hablar y decirle “Puedo entender que esté molesto y enojado”."},
        //{"¿Cuál de las siguientes afirmaciones acerca de cómo finalizar una sesión disciplinaria es VERDADERA","Escribir un resumen del plan de mejoramiento para ayudar a crear el compromiso del empleado y evitar malas interpretaciones."},
        //{"Muchos empleados del sector hotelero deben ser entrenados en una técnica que administra circulación y respiración artificial a una persona con una interrupción de la función cardíaca o pulmonar. Esta técnica es llamada","Reanimación cardiopulmonar."},
        //{"¿Qué debe hacer alguien que quiere convertirse en un supervisor multicultural destacado","Adquirir entrenamiento sobre cómo supervisar empleados de grupos diferentes."},
        //{"¿Qué son las normas éticas","Las normas acerca de lo que está “bien” y lo que está “mal”."},
        //{"¿Cuál de las siguientes pautas sirve para tomar medidas de supervisión en casos de consumo de drogas","Antes de reunirse con el empleado, asegurarse de conocer las políticas sobre el consumo de drogas de la compañía."},
        //{"Un pequeño grupo de personas comprometidas con un propósito y objetivos comunes, que crean confianza entre sí a través de un diálogo franco, se llama","equipo de trabajo."},
        //{"El supervisor de un comedor da la bienvenida a una pareja y la conduce a su asiento; un mesero los saluda y toma su pedido; el cocinero prepara la orden en la cocina; el mesero se la sirve; el supervisor despide a la pareja cuando se retira. El supervisor del comedor, el mesero y el cocinero conforman un equipo de trabajo __________","de relevos"},
        //{"Ester trabaja como mucama en el Motel ABC. El dueño del motel le ofrece una promoción a supervisora del departamento de limpieza de habitaciones. Ester le responde: “¡De ninguna manera! Los supervisores reciben todos los problemas pero ninguna de las ventajas de un puesto gerencial. ¡No, gracias! “ La respuesta de Ester indica que cuando se trata de puestos de supervisión, ella cree en","la falacia de la ausencia de poder."},
        //{"Selena esta entrevistando a Jeremías para un puesto de mesero. Le pregunta cosas como: "¿Cuáles son sus hobbies?" y "¿Tiene una mascota?". Selena sabe que es importante hacer este tipo de preguntas a los candidatos porque","los supervisores deben establecer una conexión personal con los miembros del personal antes de conectarse profesionalmente con ellos."},
        //{"¿Cuál de las siguientes afirmaciones acerca de los supervisores y el poder es VERDADERA","Los supervisores tienen mucho poder personal."},
        //{"Para mantenerse ágil y positivo en el lugar de trabajo, el supervisor debe","vivir una vida equilibrada y cuidarse a sí mismo."},
        //{"¿Qué es la "holgazanería social"","La tendencia de muchas personas a trabajar menos cuando están en equipo que cuando trabajan solos."},
        //{"Hace cuatro meses, Benjamín formó un equipo de resolución de problemas que desde entonces se ha reunido una vez por semana. Benjamín se ha dado cuenta de que la confianza entre los miembros del equipo sigue siendo baja. Las reuniones de equipo suelen ser formales y tensas. Hay confusión acerca de quién ha sido asignado a cada tarea, y los miembros del equipo están muy en desacuerdo unos con otros. Hasta ahora, Benjamín ha seguido una política de no intervención, prefiriendo dejar que los miembros del equipo encuentren su propio camino. ¿Qué debe hacer ahora","El equipo tiene problemas, y Benjamín debe tomar un papel más activo como líder."},
        //{"¿Cuál es el objetivo general del empoderamiento","Mejorar el servicio al huésped y aumentar las ganancias de la organización."},
        //{"¿Qué tipo de poder deriva de la autoridad de un gerente para negar aumentos de salarios, bajar de categoría o despedir a los empleados","Coercitivo"},
        //{"Un entorno que fomenta la motivación es un entorno donde","se establecen las metas de los empleados, y se los influencia para que logren esas metas."},
        //{"¿Cuál de las siguientes actividades rendirá resultados positivos en cualquier programa de motivación","Mantener a los empleados informados acerca de los eventos y actividades del departamento."},
        //{"¿Cuál de las siguientes actividades puede ser una herramienta de motivación valiosa para eliminar los obstáculos que puedan bloquear el crecimiento y progreso de un empleado","Capacitación interdisciplinaria."},
        //{"¿Cuáles son los empleados generalmente más motivados para tener éxito","Los empleados nuevos."},
        //{"¿Cuál de las siguientes actividades de recursos humanos le da al supervisor la oportunidad de conocer las necesidades, intereses y objetivos de los futuros empleados","Entrevistar a los candidatos a las vacantes."},
        //{"José es el supervisor del servicio de banquetes en el Country Club Ritz. Hace varios meses creó dos equipos de servicio de banquetes con los empleados más experimentados y mejor entrenados. Los equipos están empoderados para planificar, prestar y evaluar servicios de comidas en una serie de actividades que se llevan a cabo en el club. El estilo de liderazgo que José está utilizando con estos equipos es","dejar hacer."},
        //{"¿Cuál de los siguientes es un beneficio de un conflicto en una organización","Los conflictos a menudo obligan a un grupo a enfocarse en sus metas."},
        //{"¿Cuál de las siguientes afirmaciones sobre las fuentes de conflicto es VERDADERA","Para evitar conflictos, los supervisores deben tener claro el alcance de su autoridad."},
        //{"Michelle, recién promovida a supervisora del comedor, siente que debe tener el control, tomar decisiones rápidas y aceptar plena responsabilidad en la resolución de los conflictos que se presenten entre el personal a su cargo. Tiene un alto nivel de asertividad y tiende a ser dominante en el trato con otros. El estilo de resolución de conflictos que Michelle tiende a utilizar se llama","competencia"},
        //{"¿Cuál de las siguientes afirmaciones sobre el manejo de conflictos entre empleados es VERDADERA","Pedir la ayuda de los empleados involucrados para resolver el conflicto los invita a comprometerse con una solución eventual."},
        //{"Para avanzar en muchas situaciones de manejo de conflictos, los supervisores deben a menudo alentar a los empleados para que expresen claramente lo que sienten. Una de las mejores maneras de hacerlo es","hacer comentarios neutrales y sin prejuicios para reflexionar con calma sobre los sentimientos expresados por los empleados."},
        //{"Diana está a punto de comenzar una sesión para resolver un conflicto entre dos empleados. La mejor manera de abrir la sesión es decir","El trabajo de nuestro departamento se está viendo afectado por lo que parece está ocurriendo entre ustedes dos. ¿Hay algo sobre lo que quieran hablar?"},
        //{"Cuando surge un conflicto entre un supervisor y un empleado, el papel del supervisor debe ser","negociar un acuerdo teniendo en cuenta las necesidades de ambos."},
        //{"¿Cuál de las siguientes afirmaciones sobre la administración del tiempo es VERDADERA","Los supervisores crean sus propias pérdidas de tiempo cuando nunca le dicen "No" a los demás."},
        //{"¿Cuál de las siguientes es una estrategia para el manejo de las interrupciones de baja prioridad","Asignar un momento específico del día para tratar las interrupciones de baja prioridad."},
        //{"Una interrupción de alta prioridad debe","tratarse en forma inmediata."},
        //{"¿Cuál es la definición de una pérdida de tiempo","Algo que le lleva tiempo pero no le ayuda a alcanzar sus objetivos."},
        //{"Usted puede utilizar una guía de planificación semanal para asignar el tiempo a las actividades , los proyectos y las personas más importantes que debe atender durante la semana. ¿Cuál de las siguientes afirmaciones acerca de las guías de planificación semanal es VERDADERA","Conviene establecer una hora específica de cada semana para cumplimentar su guía de planificación semanal."},
        //{"Tal vez el mayor obstáculo para delegar es la creencia del supervisor de que "yo lo puedo hacer mejor". Es conocido como","falacia de omnipotencia."},
        //{"Las fuerzas de cambio _________ surgen de cambios sociales, económicos, y de condiciones políticas, legales y tecnológicas","externas"},
        //{"El Análisis del campo de fuerza es una técnica de gestión de cambio utilizada para","identificar las fuerzas impulsoras y las fuerzas limitantes en cualquier situación."},
        //{"Los empleados tienden a resistirse al cambio. Una acción clave que un supervisor puede tomar para ayudar a minimizar esta resistencia al cambio es","destacar cómo los propios empleados se beneficiarán directamente de los cambios propuestos."},
        //{"Como supervisor, usted debe entender por qué los empleados podrían resistirse a cambios específicos a fin de que usted","pueda crear estrategias para superar la resistencia de los empleados."},
        //{"Cuando explica los detalles de un cambio importante a sus empleados, lo mejor es","comunicar tanta información como sea posible."},
        //{"Después que un cambio se ha implementado","el supervisor debe hacer el seguimiento del cambio y observar cómo le están haciendo frente los empleados."},
        //{"¿Por qué son importantes los indicadores del cambio eficaz para evaluar el cambio","Los indicadores ofrecen un punto de comparación que permite medir la eficacia del cambio."},

        //        };


        public static Dictionary<string, string> EI_70_714_14_16_10_03_EN = new Dictionary<string, string>()
        {
            {"What are responsibilities shared by all staff in the food service industry?","Food safety and product quality"},
            {"Why must owners and managers carefully select, train, and coach their staff members?","They cannot personally serve every guest"},
            {"What is the temperature that is required for safe refrigerator storage of foods?","41°F (5°C)"},
            {"What is the initial control point in the food service system?","Menu Planning"},
            {"What must food service workers control when handling TCS foods?","Time and temperature"},
            {"What is an example of a food service establishment that would be considered a high-risk operation for inspection?","Nursing home"},
            {"What is an example of a priority violation in a food service operation?","Dish machine not sanitizing properly"},
            {"What is an example of an imminent health hazard that could result in the immediate closure of a food service facility?","Severe pest infestation"},
            {"During a health inspection, the inspector writes \"OUT\" next to the compliance item labeled \"Proper date marking and disposition.\" What does the OUT notation indicate?","Not in compliance with the identified requirement"},
            {"In a food service operation, who is required to be in attendance during a health inspector\'s post-inspection closing conference?","Person in charge"},
            {"What are the two broad categories of harmful microorganisms?","Pathogens and spoilage organisms"},
            {"At what control point does most food spoilage occur?","Storing"},
            {"What does the S stand for in a TCS food item?","Safety"},
            {"In addition to food and moisture, what do bacteria need to survive and reproduce?","Warm temperatures"},
            {"A bottle of hand sanitizer has leaked onto raw chicken being prepared on a grill. What type of hazard does this present?","Chemical"},
            {"Mushroom, fish, and shellfish toxins are considered what type of food safety hazard?","Biological"},
            {"Human hair is found in a bowl of soup. What type of safety hazard is this considered?","Physical"},
            {"What is a foodborne illness that is preventable by vaccination?","Hepatitis A"},
            {"What is the first step food service workers must take when washing their hands properly?","Place hands under clean, running warm water"},
            {"What is a type of jewelry acceptable to wear during food preparation?","Plain ring"},
            {"What is the most critical reason employer-paid sick leave is important for food safety?","It prevents sick employees from coming to work"},
            {"What is the minimum number of hours that must pass before staff members who were excused from work for having diarrhea or vomiting can return to work?","24"},
            {"Who conducts and documents an in-house follow-up inspection to help prevent the reoccurrence of a suspected foodborne illness outbreak?","The operation\'s manager"},
            {"Why is it important that a manager take detailed notes during the investigation of a foodborne illness complaint?","Notes may be beneficial for a later investigation"},
            {"A manager\'s goal when utilizing a rationalized menu is the identification of ingredients that","may be used in a variety of menu items."},
            {"What is the term used to describe the process of preparing and serving as many menu items as possible with a limited number of raw ingredients?","Cross utilization"},
            {"What factor most directly affects a food operation\'s purchasing, receiving, and storage requirements?","The operation\'s menu"},
            {"What key staff-related control point should managers consider at the menu planning point?","All staff members are familiar with allergens present in the menu offerings"},
            {"Why are preshift lineup meetings important in food service operations?","Provides information regarding new menu items, allergen awareness, special promotions or tasks before service begins"},
            {"A manager decides to expand a menu to include made-from-scratch soup that is to be sold cold. What equipment should this manager consider purchasing?","A blast chiller to rapidly cool down soup to safe cold-holding temperatures"},
            {"What are two important factors a food service operator should consider when purchasing a new mixer to be used for making large batches of tomato sauce?","Adherence to safety standards and listing by accredited listing organizations"},
            {"What is the main advantage of utilizing speed-scratch menu items?","Reduces preparation time by combining pre-made products with fresh ingredients."},
            {"What is an innovative way to keep up with increases to ingredient and labor costs without upsetting customers?","Introducing new test appetizers to eventually become value-added menu items"},
            {"What is the average amount of their total revenue that food service operations spend on product purchasing?","30 to 50 percent"},
            {"What is a disadvantage of buying low-quality food products at bargain prices?","Increases an operation\'s food safety-related risks."},
            {"What managerial action would have the most adverse effect on the purchasing control point?","Buying into a great deal with substantial savings if an item is purchased in bulk quantity"},
            {"What purchasing-related document would an operator find a menu item\'s portion size?","Food safety and quality sheet"},
            {"What control form is prepared by an operation’s buyer and contains the details of the items to be bought from a single distributor?","Purchase Order"},
            {"What must a buyer know about a raw ingredient to properly calculate the ingredient\'s edible portion (EP) cost?","The product\'s yield percentage"},
            {"Beef quality grading is based on the beef\'s level of marbling, as well as its","degree of maturity."},
            {"What is the minimum number of days food service operators must retain shellstock identification tags?","90"},
            {"When does an operation take ownership of the food and beverage products that it buys?","When the products are received"},
            {"As part of the quality management system, documentation must be on file to show that all receiving staff has completed training in food","safety."},
            {"What type of experience is essential for a receiver in a food service operation?","Food production"},
            {"What type of thermometer will register accurate temperatures in the shortest amount of time?","Thermocouple"},
            {"Time-temperature indicators (TTI) are valuable during receiving because they indicate:","time-temperature abuse during transportation."},
            {"What is the formula food service operators use to calculate their food cost percentage?","Net Food Cost ÷ Total Sales During the Period"},
            {"When using the FIFO inventory management system, which types of food items should be used first?","Oldest items"},
            {"How can food buyers reduce their operations\' cost per unit purchased?","Buy in larger quantities"},
            {"At what control point is food at its highest risk of tampering?","Storing"},
            {"What is the maximum allowable temperature in frozen food storage areas?","0°F (–17.8°C)"},
            {"What is an improper way to thaw a frozen TCS food in an operation?","Thaw and refreeze it"},
            {"When storing refrigerated foods by their minimal internal cooking temperatures, which foods should be stored on the uppermost (top) shelves?","Ready-to-eat foods"},
            {"What management activity helps ensure that food equipment and their storage areas are regularly cleaned and sanitized?","Developing written schedules detailing responsibilities"},
            {"Where should toxic and poisonous materials be stored in a food service operation?","In locked areas and away from all food products"},
            {"What is the temperature danger zone for TCS foods?","41°F (5°C) to 135°F (57°C)"},
            {"How do food service managers demonstrate their proficiency in food safety?","Passing an accredited test"},
            {"Food service operators must prevent unauthorized persons from entering food production areas because such persons can pose risks to security and","food safety."},
            {"What is a TCS food that should remain unwashed before it is cooked?","Raw poultry"},
            {"What type of equipment cooks food by using a fan to force hot air into direct contact with the food?","Convection oven"},
            {"What food service characteristic results in the need to hold cooked foods?","Business peaks and valleys"},
            {"To be held safely, foods that are to be held or displayed cold must maintain maximum internal temperatures of","41°F (5°C)."},
            {"In what service style do servers prepare and serve ordered menu items in front of guests?","Cart service"},
            {"What leftover banquet foods may safely be served a second time?","Non-TCS food that is still packaged and in sound condition."},
            {"What service items may be reused by guests who want to obtain additional items from self-service food bars?","Glasses"},
            {"What is the maximum amount of time that should pass between checking temperatures in self-service food bars to help minimize the risk of serving food that is unsafe to eat?","120 minutes"},
            {"What is meant by the term \"honestly presented food?\"","Presented in a way that does not mislead or misinform guests"},
            {"How may guests properly serve themselves ice cubes for use in their beverages?","From automatic dispensers"},
            {"The role of an expediter in a food service operation is to be a communication link between","kitchen staff and service staff."},
            {"Guests who enter a food service operation with service animals are allowed to go in all areas","where the general public are allowed to go."},
            {"In what setting would a food service operator most likely need to obtain a temporary food service establishment license?","County fair"},
            {"What type of water must be available for use in cleaning temporary food service establishments?","Potable"},
            {"Who must take ownership of the complaint from a dissatisfied food service guest?","Staff member who first becomes aware of the complaint"},
            {"What should the managers or owners of a food service operation ask a dissatisfied guest to do if the guest posts a negative comment on a social media site?","Contact the manager or owner by phone or in person"},
            {"What is the process by which microorganisms on a surface are reduced to a safe level?","Sanitizing"},
            {"Metal cleaners and polishers are oil-based products designed to remove both soil and","oxidation."},
            {"What is the most expensive type of sanitizer commonly used in food service operations?","Iodine based"},
            {"What is the type of sanitizer that requires the least amount of exposure time to work properly?","Chlorine based"},
            {"All cleaners and sanitizers MUST be clearly labeled and stored in a locked area away from food because they are","toxic chemicals."},
            {"What cleaning tool does the Food Code prohibit food service workers from using when making the final sanitizing wipe of a food contact surface?","Sponge"},
            {"A written cleaning schedule should indicate who is responsible for each cleaning task and","how often the task should be completed."},
            {"When no chemical sanitizer is utilized, what is the minimum water temperature normally required to properly sanitize manually washed pots and pans?","171°F (77°C)"},
            {"What external circumstance has caused many food service operators to purchase chemical-sanitizing dish machines?","Rising energy costs"},
            {"What is an external factor that could result in a need to reevaluate a food service operation\'s cleaning and maintenance program?","Advancements in cleaning technology"},
            {"What is one primary piece of information recorded in a maintenance and repairs equipment log?","Installation of replacement parts"},
            {"Where must food service workers dispose of used mop water?","Utility sink"},
            {"What term describes potable (drinking water) becoming contaminated by non-potable water due to an improper plumbing arrangement?","Cross connection"},
            {"What is an example of an unsafe food storage practice?","Staging canned goods on racks in a restroom closet"},
            {"When must a food-establishment plan review be developed and submitted to the local regulatory authority?","A currently operating business is to be extensively remodeled"},
            {"In what group of individuals is the incidence of food allergies worldwide believed to be more common?","Children younger than 18"},
            {"What are symptoms that may be exhibited by a person going into anaphylactic shock from consuming foods with allergens?","Hives, swelling of the face, tongue, lips, or difficulty breathing"},
            {"What is a common cause of food allergy incidents in food service operations?","Lack of communication"},
            {"How do managers begin the creation of a food allergen control program?","Menu planning"},
            {"What is an example that exemplifies cross-contact from allergens?","Using the same ice cream scoop to serve maple walnut and then vanilla ice cream"},
            {"In a food service operation, best practices for preparing and serving food for guests with allergies should be clearly written and","frequently reviewed with the operation\'s staff."},
            {"What group does active managerial control (AMC) involve to create a food safety culture?","Food service staff"},
            {"What entity does HACCP identify as the final party responsible for food safety?","Food establishment"},
            {"What is a benefit of implementing automated systems in a food service operation?","Assisting in compliance with food safety requirements"},
            {"The primary value of automatic temperature-sensor monitoring and logging systems is that they help staff","identify food products in unsafe storage conditions."},
            {"Social media has helped in monitoring food safety issues by","detecting unreported cases of foodborne illness."},
            //{"What does the S stand for in a TCS food item?","Safety"},
        };
        public static Dictionary<string, string> EI_70_701_14_16_10_06_EN = new Dictionary<string, string>()
        {
            {"In a hospitality organization, who is primarily responsible for directing the work of entry-level employees","Supervisor"},
            {"Who is considered part of top-level management in a large hospitality organization","CEO"},
            {"What management principle states each employee should have only one boss","Unity of command"},
            {"What is the type of authority supervisors hold because of their abilities and personal traits","Informal"},
            {"An organization's long-range plan will typically cover a period of three to fiv","years."},
            {"What must supervisors do before they begin developing a formal plan","Establish goals"},
            {"What term describes an experienced supervisor who advises a less experienced supervisor about jobs and career paths","Mentor"},
            {"When supervisors provide a safe working environment, they are fulfilling their responsibilities to thei","employees."},
            {"What common criteria is used to define a millennial employee","Age"},
            {"What can supervisors do to better engage millennial employees","Create balanced life and work schedule"},
            {"Skilled supervisors adjust their approach based on their available resources an","each unique situation."},
            {"What can effective supervisors do to improve themselves","Set specific career goals"},
            {"Supervisors who form general opinions about certain groups of workers rather than think of each employee as an individual can be biased because o","stereotyping."},
            {"Being aware of the potential danger of making assumptions based on first impressions is especially important when supervisors ar","interviewing job candidates."},
            {"Which portion of a conversation or speech should indicate what the speaker wants the listener to do as a result of the communication","Conclusion"},
            {"What action can speakers take to emphasize main points in their formal presentations","Move nearer the audience"},
            {"What is an example of inactive listening","Focusing on only one part of the speaker's message."},
            {"What stage of active listening do listeners separate facts from a speaker's opinions","Evaluating"},
            {"What is an example of a listener's self-disclosure statement","I remember the same thing happening to me."},
            {"What is an important factor that influences how workplace listeners interpret their boss's nonverbal communication","Cultural background"},
            {"An employee is offended when touched by his supervisor's left hand. What personal characteristic is most likely the reason for this employee's reaction","Cultural background"},
            {"A supervisor prepares a document summarizing the duties, working conditions, and activities of a specific job. What document is the supervisor preparing","Job description"},
            {"What selection tool lists the critical knowledge, skills, and experience needed to do a job properly","Job specification"},
            {"An employee is allowed to work four ten-hour days to complete her 40-hour week.  This is an example o","compressed scheduling."},
            {"What job position increases a hotel worker's opportunity for telecommuting","Reservationist"},
            {"What is an example of a closed question used in a hiring interview","Are you available to work week-ends?"},
            {"A business could be found guilty of negligent hiring if i","fails to exercise reasonable care when selecting employees."},
            {"What is an example of an activity that would take place in a hotel's induction orientation","Instructions on setting up a housekeeping cart"},
            {"What is an advantage of holding group session orientations","Providing consistency for all new employees"},
            {"What is an advantage of holding mentor session orientations","Helping experienced employees brush up on their own skills"},
            {"The three S's addressed in most hospitality training programs are standards, safety, an","service."},
            {"In what form of training is the trainer's main job the encouragement of participative learning and mutual problem solving","Group"},
            {"What must supervisors utilize to identify the retraining needs of their experienced employees","Performance evaluations"},
            {"What training tool identifies the most important tasks employees must be able to perform in their jobs","Job description"},
            {"In what step of the training process is it most important for trainers to avoid the use of industry jargon","Conduct the training"},
            {"After training, many trainers fail to correct their employees because these trainer","don't want to offend their trainees."},
            {"A return on investment in training measures the benefits of training in relation to th","costs of doing training."},
            {"What must trainers do if they find their trainings sessions have not been successful","Understand the factors that create training problems"},
            {"A hospitality operation wastes $200 due to over scheduling. The operation achieves at 10 percent profit on revenue. How much revenue must the operation generate to replace the $200 over scheduling loss","$2,000"},
            {"Supervisors must create weekly employee work schedules based on productivity standards and thei","business volume forecasts."},
            {"What will be the effect of consistently understaffing a hospitality operation","Short-term reduction in labor costs, and long-term reduction in revenue and profits"},
            {"What is the alternative scheduling technique in use when a supervisor schedules the same employee to work two separate time periods on the same day","Split shift"},
            {"What is the best alternative scheduling approach to use if a hotel's banquet manager has an infrequent need for a very large number of banquet servers","Increase the number of temporary employees"},
            {"What is a tool supervisors can use to help generate ideas for new ways to get a job done","Guest comments"},
            {"In a restaurant, what is a required activity that would be a good candidate for outsourcing","Exhaust hood cleaning"},
            {"A recency error occurs if a supervisor primarily evaluates an employee based on that employee'","latest work performance."},
            {"Using a 1 (poor) to 10 (best) worker performance rating system, a supervisor rates nearly all employees as a 2 or 3. What is the performance evaluation error this supervisor is in danger of committing","Severity error"},
            {"During an employee performance review, a supervisor points out an employee's performance gap. What should be this supervisor's immediate next step","Seek to understand possible causes of the performance gap"},
            {"During an employee evaluation session, what is an inappropriate way for a supervisor to address an employee who is frequently late to work","You never come in on time."},
            {"Supervisors who make sure their employees are accurately informed about a company's objectives and challenges are helping to foster a proper work environment by changing employe","attitudes."},
            {"What supervisory activity is usually unplanned and performed at an employee's work station","Informal coaching"},
            {"What is the optimum number of performance goals a coach should establish with an employee","1 to 4"},
            {"What can supervisors do as long as they apply the same set of values and goals to assess every situation","Address discipline-related challenges on an individual basis"},
            {"What is the discipline-related myth believed by a supervisor who begins to resent employees taking advantage of her leniency","If you are nice to your employees they won't need discipline"},
            {"When should employees be informed about major changes in work rules and policies","Before the changes are made"},
            {"The role of a supervisor who properly utilizes discipline is similar to that of ","coach."},
            {"For positive reinforcement to be effective, supervisors must do it in a timely way an","in ways employees find meaningful."},
            {"When supervisors discuss a future disciplinary action to be taken, they must describe what the action will be an","when the action will be taken."},
            {"What is an example of a loaded question used to identify a performance problem","Didn't you know this would happen?"},
            {"What must be true about the actions of sexual harassers","They  are unwelcome"},
            {"What is the first action supervisors should take when receiving a sexual harassment complaint","Inform their boss or human resources department"},
            {"What is the first aid technique supervisors use to aid choking victims","Heimlich maneuver"},
            {"What is the first action supervisors must take when assisting a choking victim","Send someone for help"},
            {"Why will employees from different cultural backgrounds better understand the needs of those guests from similar backgrounds","They can speak the guests' language"},
            {"Supervisors with a multicultural work force must take extra care not to offend their workers when the supervisor","attempt to be funny or tell jokes."},
            {"What types of hospitality properties benefit most when their employees speak languages other than the one commonly spoken in the local community","Properties serving international guests"},
            {"Ethics involves making decisions about what i","right or wrong in dealing with others."},
            {"What group would normally develop the ethical standards to be used by members of a specific profession","Professional associations"},
            {"A supervisor's decision in a grey area is likely ethical if the superviso","would like the decision to be made public."},
            {"When making decisions with ethical implications, supervisors should most consider the decisions' long-term impact on thei","businesses."},
            {"A work team can only attract and keep effective team members if the members shar","agreed upon core values."},
            {"What do team members gain when they adopt a life-long commitment to learning","Increased value, integrity, or knowledge"},
            {"The best leaders consistently seek to exceed their guests' expectations and t","meet their organization's goals."},
            {"What are supervisors' primary goals when they practice “management by wandering around?","Connecting with employees on a personal level"},
            {"Supervisors become optimally effective team leaders when the","get to know their team's members individually."},
            {"What are two of the best tools supervisors can use to improve employee motivation and department morale","Performance evaluations and coaching"},
            {"What activity can supervisors use to keep employees from feeling they are locked into a particular job","Cross-training"},
            {"Employees will be encouraged to participate in formal suggestion programs when all their submitted suggestion","receive a response."},
            {"How can supervisors best obtain suggestions for immediately addressing an important matter, or problem area, that is of property-wide interest","Form a task group or work committee to make suggestions"},
            {"What is the conflict management style that most often forces win-lose outcomes","Competition"},
            {"What conflict management style occurs when a supervisor wants to make sure each party in a conflict is allowed to partially satisfy some of their needs and concerns","Compromise"},
            {"Which method of conflict management can result in win-win or negative outcomes","Compromise"},
            {"What is the primary factor supervisors must consider when selecting a meeting location to negotiate a conflict","The nature of the conflict"},
            {"When is disciplinary action necessary","When the employee does not follow through with an agreed upon plan"},
            {"The first step in managing time is","Conducting a time analysis"},
            {"Which is an appropriate method of dealing with low priority interruptions","Set aside a brief daily time slot for open conversations with employees"},
            {"Which categories are time robbers divided into","Those you create and those others create"},
            {"To be effective time planning should be done at which two frequencies","Daily and weekly"},
            {"When a big project is divided into smaller parts, which parts should be included in a daily to-do list","Only the most important parts that must be done that day."},
            {"While developing a new process, the manager involves key employees in the planning stages. Why will this help overcome resistance to change","The employees will feel a level of ownership in the change."},
            {"What is the MOST important factor in implementing change successfully","Maintaining an atmosphere of trust and respect in all interactions with employees."},
            {"Even when an anticipated change is already clearly defined, what approach can a manager use to improve employee support for change","Ask the employees for ideas on how to achieve the planned change"},
            {"A supervisor asked employees for their opinions and feelings about a proposed change. What should he/she do next","Listen and observe, reflect the employees' feelings and opinions, and check for understanding."},
            {"Which approach supports the principle of making a promotion a possibility","Develop the skills needed for the position you want"},
            {"Who knows the most about an individual's skills, interests, and values","The individual"},
            {"Which roles does a mentor play","Coach, advisor, teacher"},
            {"What matters MOST in a professional development plan","Excellence and movement toward excellence"},
            {"Which method can be used to set goal priorities","Build up strengths in highest interest areas first."},
            {"Which behavior does a visual learner perform","Use highlighters when reading."},
            {"What is an example of an on-the-job learning activity","Volunteering to serve on a cross-functional team."}
        };


    }
}
